<?php

namespace ApprentisBundle\Repository;

/**
 * ApprentisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprentiRepository extends \Doctrine\ORM\EntityRepository
{
	public function findPromotion($promotion){//$promotion){
		$query = $this->getEntityManager()->createQuery(
		'SELECT a
			FROM ApprentisBundle:Apprenti a
			JOIN ApprentisBundle:Promotion p
			WHERE p.proPromotion=:promotion
			ORDER BY a.appNom ASC'
			
		
		);
		//
		
		$query->setParameter('promotion',$promotion);
		
		return $query->getResult();	
	}
}
?>